import SwiftSyntax

indirect enum Composition {
    case property(String, Composition)
    case optional(Composition)
    case array(Composition)
    case identifiableArray(id: TypeSyntax, value: Composition)
    case dictionary(key: TypeSyntax, value: Composition)
    case named(TypeSyntax)
}

struct Parameter {
    let label: String?
    let type: TypeSyntax
}

enum AutogeneratedImplementation {
    case updateStateProperty(String)
}

struct Action {
    let label: String
    let parameters: [Parameter]
    let composition: Composition?
    let implementation: AutogeneratedImplementation?
}

struct DetachmentRef {
    let typename: String
    let methodName: String
}

struct Component {
    let name: String
    let compositions: [Composition]
    let actions: [Action]
    let detachments: [DetachmentRef]
    let hasDefinedOutput: Bool
    let translateCompositionMethodNames: [String: String]
}
